import { Role, VerificationStatus, VerificationTier } from '../constants';
import type { User } from '../types';

export const ADMIN_USER: User = {
  id: 'user_admin_001',
  name: 'Tandong Fuet',
  email: 'tandongfuet6700@gmail.com',
  role: Role.Admin,
  createdAt: '2023-01-01T10:00:00Z',
  accountBalance: 1000000,
  pendingBalance: 0,
  totalEarnings: 0,
  status: 'Active',
  verificationStatus: VerificationStatus.Verified,
  verificationTier: VerificationTier.Gold,
  sellerReviewCount: 0,
  averageSellerRating: 0,
  isTestUser: true,
  followers: [],
  followerCount: 0,
  following: [],
  savedArticleIds: [],
  badges: ['badge_founder', 'badge_trusted'],
  wishlist: [],
  isFirstLogin: false,
};

export const SEED_USERS: User[] = [
    {
        id: `user_1760056381327_1`, name: 'Efuet Amin', email: 'efuetg@gmail.com', role: Role.Farmer, createdAt: new Date().toISOString(), accountBalance: 500000,
        pendingBalance: 0, totalEarnings: 0, status: 'Active', 
        verificationStatus: VerificationStatus.Verified, verificationTier: VerificationTier.Bronze,
        sellerReviewCount: 15, averageSellerRating: 4.8, hasReceivedSupportGrant: true, hasSeenGrantToast: true, followers: [], followerCount: 0,
        following: [], savedArticleIds: [],
        badges: [],
        wishlist: [],
        isFirstLogin: false,
        location: 'Bamenda',
    },
    {
        id: `user_1760056381327_2`, name: 'Farmer Test', email: 'farmer@test.com', role: Role.Buyer, createdAt: new Date().toISOString(), accountBalance: 150000,
        pendingBalance: 0, totalEarnings: 0, status: 'Active', 
        verificationStatus: VerificationStatus.NotSubmitted, verificationTier: VerificationTier.None,
        sellerReviewCount: 0,
        averageSellerRating: 0,
        hasReceivedSupportGrant: false, hasSeenGrantToast: false, followers: [], followerCount: 0,
        following: [], savedArticleIds: [],
        badges: [],
        wishlist: [],
        isFirstLogin: true, // This user will get the onboarding tour
    },
    {
        id: `user_1760056381327_3`, name: 'Ex Servico', email: 'ex@gmail.com', role: Role.ServiceProvider, createdAt: new Date().toISOString(), accountBalance: 250000,
        pendingBalance: 0, totalEarnings: 0, status: 'Active', 
        verificationStatus: VerificationStatus.Verified, verificationTier: VerificationTier.Silver,
        sellerReviewCount: 8, averageSellerRating: 4.5, hasReceivedSupportGrant: false, hasSeenGrantToast: false, followers: [], followerCount: 0,
        following: [], savedArticleIds: [],
        badges: [],
        wishlist: [],
        isFirstLogin: false,
        location: 'Limbe',
    },
    {
        id: `user_1760056381327_4`, name: 'Support Agent', email: 'suport@gmail.com', role: Role.SupportAgent, createdAt: new Date().toISOString(), accountBalance: 0,
        pendingBalance: 0, totalEarnings: 0, status: 'Active', 
        verificationStatus: VerificationStatus.Verified, verificationTier: VerificationTier.None,
        sellerReviewCount: 0,
        averageSellerRating: 0,
        hasReceivedSupportGrant: false, hasSeenGrantToast: false, followers: [], followerCount: 0,
        following: [], savedArticleIds: [],
        badges: [],
        wishlist: [],
        isFirstLogin: false,
    },
    {
        id: `user_test_farmer_1`, name: 'Admin Farmer', email: 'admin@test.com', role: Role.Farmer, createdAt: new Date().toISOString(), accountBalance: 500000,
        pendingBalance: 0, totalEarnings: 0, status: 'Active', 
        verificationStatus: VerificationStatus.Verified, verificationTier: VerificationTier.Bronze,
        sellerReviewCount: 0, averageSellerRating: 0, hasReceivedSupportGrant: true, hasSeenGrantToast: false, followers: [], followerCount: 0,
        following: [], savedArticleIds: [],
        badges: [],
        wishlist: [],
        isFirstLogin: true,
        location: 'Bafoussam',
    },
];