import React, { createContext, useState, useContext, useMemo, useCallback } from 'react';

type Language = 'en' | 'fr' | 'pi'; // English, French, Pidgin

const translations = {
  en: {
    home: 'Home',
    marketplace: 'Marketplace',
    community: 'Community',
    seasonalCalendar: 'Seasonal Calendar',
    about: 'About Us',
    contactUs: 'Contact Us',
    notifications: 'Notifications',
    markAllAsRead: 'Mark all as read',
    noNotifications: 'No notifications yet.',
    viewAllNotifications: 'View All Notifications',
    dashboard: 'Dashboard',
    settings: 'Settings',
    adminPanel: 'Admin Panel',
    logout: 'Logout',
    login: 'Login',
    signUp: 'Sign Up',
    welcome: 'Welcome',
    dashboardGreeting: "Here's what's happening on your dashboard today.",
    
    // Tabs
    tabOverview: 'Overview',
    tabListings: 'My Listings',
    tabServices: 'My Services',
    tabOrders: 'Incoming Orders',
    tabBookings: 'Bookings',
    tabCommunity: 'Community',
    tabDisputes: 'My Disputes',
    tabAnalytics: 'Analytics',
    tabWallet: 'Wallet',
    tabVerification: 'Verification',
    tabMessages: 'Messages',
    tabReviews: 'Reviews',
    tabMyOrders: 'My Orders',
    tabMyBookings: 'My Bookings',
    tabFavorites: 'Wishlist',
    tabSavedArticles: 'Saved Articles',
    tabCalendarAlerts: 'Calendar Alerts',
    tabProfileAndVerification: 'Profile & Verification',
    tabFollowing: 'Following',
    tabRecipes: 'Recipe Assistant',
    tabAdminAnalytics: 'Analytics',
    tabAdminFinances: 'Finances',
    tabAdminSecurity: 'Security Alerts',
    tabAdminModeration: 'Moderation',
    tabAdminUsers: 'Users',
    tabAdminListings: 'Listings',
    tabAdminVerifications: 'Verifications',
    tabAdminDisputes: 'Disputes',
    tabAdminContent: 'Content',
    tabAdminMap: 'Map View',
    tabAdminLogs: 'Activity Logs',
    
    // Forms & Buttons
    addNewListing: 'Add New Listing',
    addNewService: 'Add New Service',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm',
    submit: 'Submit',
    saveChanges: 'Save Changes',
    search: 'Search',
    clearFilters: 'Clear All Filters',
    
    // Marketplace
    marketplaceTitle: 'Marketplace',
    marketplaceSubtitle: 'Discover fresh produce and essential services from local sellers.',
    filtersTitle: 'Filters',
    gridView: 'Grid',
    mapView: 'Map',
    searchFilter: 'Search',
    regionFilter: 'Region',
    categoryFilter: 'Category',
    sortByFilter: 'Sort By',
    categoryAll: 'All',
    categoryVegetables: 'Vegetables',
    categoryFruits: 'Fruits',
    categoryGrains: 'Grains',
    categoryLivestock: 'Livestock',
    categoryPoultry: 'Poultry',
    categoryTools: 'Tools',
    categoryFertilizers: 'Fertilizers',
    categoryCrafts: 'Crafts',
    categoryServices: 'Services',
    sortNewest: 'Newest Arrivals',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',

    // Footer
    footerTagline: 'Connecting Cameroonian farmers to the world.',
    support: 'Support',
    faqLink: 'FAQ',
    termsLink: 'Terms of Service',
    privacyLink: 'Privacy Policy',
    feesPolicy: 'Fees & Commission Policy',
    newsletterTitle: 'Stay in the Loop',
    newsletterDescription: 'Subscribe for the latest updates on fresh produce, new services, and special offers.',
    subscribe: "Subscribe",
    quickLinks: 'Quick Links',
    joinUs: 'Join Us',
    joinAsFarmer: 'Join as a Farmer',
    joinAsBuyer: 'Join as a Buyer',
    joinAsServiceProvider: 'Join as a Service Provider',
    // Login Page
    signInTitle: 'Sign in to your account',
    signInSubtitle: 'Or',
    startJourneyLink: 'start your journey with us',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    signInButton: 'Sign in',
    emailPlaceholder: 'Enter your email address',
    passwordPlaceholder: 'Enter your password',
    // Register Page
    createAccountTitle: 'Create your account',
    createAccountSubtitle: 'Already have an account?',
    firstNameLabel: 'First Name',
    lastNameLabel: 'Last Name',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    roleLabel: 'I am a...',
    buyerRole: 'Buyer',
    farmerRole: 'Farmer',
    serviceProviderRole: 'Service Provider',
    adminRole: 'Admin',
    supportAgentRole: 'Support Agent',
    createAccountButton: 'Create Account',
    restrictedRoleMessage: '🔒 This role requires verification. Please log in with your authorized credentials.',
    proceedToLoginButton: 'Proceed to Login',
    firstNamePlaceholder: 'e.g., John',
    lastNamePlaceholder: 'e.g., Doe',
    confirmPasswordPlaceholder: 'Confirm your password',
    socialLoginSeparator: 'Or continue with',
    signUpWithGoogle: 'Sign up with Google',
    signUpWithFacebook: 'Sign up with Facebook',
    signUpWithApple: 'Sign up with Apple',
    iHaveReadAndAgree: 'I have read and agree to the',
    feesAndCommissionPolicyLink: 'Fees & Commission Policy',
    passwordWeak: 'Weak',
    passwordMedium: 'Medium',
    passwordStrong: 'Strong',
    passwordIsWeakError: 'Password is too weak.',
    // Cart Page
    cartTitle: 'Your Shopping Cart',
    removeItem: 'Remove',
    deliveryOptionsTitle: 'Delivery Options',
    orderSummaryTitle: 'Order Summary',
    walletBalance: 'Your balance',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery',
    orderTotal: 'Order total',
    estDelivery: 'Estimated Delivery',
    placeOrderButton: 'Place Order',
    continueShopping: 'Continue Shopping',
    // Settings Page
    settingsTitle: 'Account Settings',
    settingsProfile: 'Profile',
    settingsSecurity: 'Security',
    settingsNotifications: 'Notifications',
    settingsAccount: 'Account',
    // Community Page
    communityTitle: 'Community Hub',
    communitySubtitle: 'Connect, share, learn, and get AI-powered help.',
    communityForum: 'Community Forum',
    educationalHub: 'Educational Hub',
    agrobotAI: 'AgroBot AI',
    newPost: 'New Post',
    // Seasonal Calendar
    calendarTitle: 'Seasonal Task Calendar',
    calendarSubtitle: "A professional guide to agricultural activities in Cameroon, tailored to your needs.",
    filterCrop: 'Crop',
    filterRegion: 'Region',
    downloadPrint: 'Download/Print',
  },
  fr: {
    home: 'Accueil',
    marketplace: 'Marché',
    community: 'Communauté',
    seasonalCalendar: 'Calendrier Saisonnier',
    about: 'À Propos',
    contactUs: 'Contactez-Nous',
    notifications: 'Notifications',
    markAllAsRead: 'Tout marquer comme lu',
    noNotifications: 'Aucune notification pour le moment.',
    viewAllNotifications: 'Voir toutes les notifications',
    dashboard: 'Tableau de bord',
    settings: 'Paramètres',
    adminPanel: "Panneau d'administration",
    logout: 'Déconnexion',
    login: 'Connexion',
    signUp: "S'inscrire",
    welcome: 'Bienvenue',
    dashboardGreeting: "Voici ce qui se passe sur votre tableau de bord aujourd'hui.",
    
    // Tabs
    tabOverview: 'Aperçu',
    tabListings: 'Mes Annonces',
    tabServices: 'Mes Services',
    tabOrders: 'Commandes Entrantes',
    tabBookings: 'Réservations',
    tabCommunity: 'Communauté',
    tabDisputes: 'Mes Litiges',
    tabAnalytics: 'Analyses',
    tabWallet: 'Portefeuille',
    tabVerification: 'Vérification',
    tabMessages: 'Messages',
    tabReviews: 'Avis',
    tabMyOrders: 'Mes Commandes',
    tabMyBookings: 'Mes Réservations',
    tabFavorites: 'Favoris',
    tabSavedArticles: 'Articles Enregistrés',
    tabCalendarAlerts: 'Alertes Calendrier',
    tabProfileAndVerification: 'Profil & Vérification',
    tabFollowing: 'Abonnements',
    tabRecipes: 'Assistant Recettes',
    tabAdminAnalytics: 'Analyses',
    tabAdminFinances: 'Finances',
    tabAdminSecurity: 'Alertes de Sécurité',
    tabAdminModeration: 'Modération',
    tabAdminUsers: 'Utilisateurs',
    tabAdminListings: 'Annonces',
    tabAdminVerifications: 'Vérifications',
    tabAdminDisputes: 'Litiges',
    tabAdminContent: 'Contenu',
    tabAdminMap: 'Vue Carte',
    tabAdminLogs: "Journaux d'activité",
    
    // Forms & Buttons
    addNewListing: 'Ajouter une Annonce',
    addNewService: 'Ajouter un Service',
    edit: 'Modifier',
    delete: 'Supprimer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    submit: 'Soumettre',
    saveChanges: 'Enregistrer',
    search: 'Rechercher',
    clearFilters: 'Effacer les filtres',

    // Marketplace
    marketplaceTitle: 'Marché',
    marketplaceSubtitle: 'Découvrez des produits frais et des services essentiels des vendeurs locaux.',
    filtersTitle: 'Filtres',
    gridView: 'Grille',
    mapView: 'Carte',
    searchFilter: 'Rechercher',
    regionFilter: 'Région',
    categoryFilter: 'Catégorie',
    sortByFilter: 'Trier par',
    categoryAll: 'Tout',
    categoryVegetables: 'Légumes',
    categoryFruits: 'Fruits',
    categoryGrains: 'Céréales',
    categoryLivestock: 'Bétail',
    categoryPoultry: 'Volaille',
    categoryTools: 'Outils',
    categoryFertilizers: 'Engrais',
    categoryCrafts: 'Artisanat',
    categoryServices: 'Services',
    sortNewest: 'Plus récents',
    sortPriceAsc: 'Prix: Croissant',
    sortPriceDesc: 'Prix: Décroissant',

    // Footer
    footerTagline: 'Connecter les agriculteurs camerounais au monde.',
    support: 'Soutien',
    faqLink: 'FAQ',
    termsLink: "Conditions d'utilisation",
    privacyLink: 'Politique de confidentialité',
    feesPolicy: 'Politique des frais et commissions',
    newsletterTitle: 'Restez Informé',
    newsletterDescription: 'Abonnez-vous pour les dernières mises à jour sur les produits frais, les nouveaux services et les offres spéciales.',
    subscribe: "S'abonner",
    quickLinks: 'Liens Rapides',
    joinUs: 'Rejoignez-Nous',
    joinAsFarmer: 'Devenir Agriculteur',
    joinAsBuyer: 'Devenir Acheteur',
    joinAsServiceProvider: 'Devenir Fournisseur',
    // Login Page
    signInTitle: 'Connectez-vous à votre compte',
    signInSubtitle: 'Ou',
    startJourneyLink: 'commencez votre voyage avec nous',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié?',
    signInButton: 'Se connecter',
    emailPlaceholder: 'Entrez votre adresse e-mail',
    passwordPlaceholder: 'Entrez votre mot de passe',
    // Register Page
    createAccountTitle: 'Créez votre compte',
    createAccountSubtitle: 'Vous avez déjà un compte?',
    firstNameLabel: 'Prénom',
    lastNameLabel: 'Nom de famille',
    emailLabel: 'Adresse e-mail',
    passwordLabel: 'Mot de passe',
    confirmPasswordLabel: 'Confirmez le mot de passe',
    roleLabel: 'Je suis un...',
    buyerRole: 'Acheteur',
    farmerRole: 'Agriculteur',
    serviceProviderRole: 'Fournisseur de services',
    adminRole: 'Administrateur',
    supportAgentRole: 'Agent de Support',
    createAccountButton: 'Créer un compte',
    restrictedRoleMessage: '🔒 Ce rôle nécessite une vérification. Veuillez vous connecter avec vos identifiants autorisés.',
    proceedToLoginButton: 'Aller à la connexion',
    firstNamePlaceholder: 'ex: Jean',
    lastNamePlaceholder: 'ex: Dupont',
    confirmPasswordPlaceholder: 'Confirmez votre mot de passe',
    socialLoginSeparator: 'Ou continuer avec',
    signUpWithGoogle: "S'inscrire avec Google",
    signUpWithFacebook: "S'inscrire avec Facebook",
    signUpWithApple: "S'inscrire avec Apple",
    iHaveReadAndAgree: "J'ai lu et j'accepte la",
    feesAndCommissionPolicyLink: 'Politique des frais et commissions',
    passwordWeak: 'Faible',
    passwordMedium: 'Moyen',
    passwordStrong: 'Fort',
    passwordIsWeakError: 'Le mot de passe est trop faible.',
    // Cart Page
    cartTitle: 'Votre panier',
    removeItem: 'Retirer',
    deliveryOptionsTitle: 'Options de livraison',
    orderSummaryTitle: 'Résumé de la commande',
    walletBalance: 'Votre solde',
    subtotal: 'Sous-total',
    deliveryFee: 'Livraison',
    orderTotal: 'Total de la commande',
    estDelivery: 'Livraison estimée',
    placeOrderButton: 'Passer la commande',
    continueShopping: 'Continuer vos achats',
    // Settings Page
    settingsTitle: 'Paramètres du compte',
    settingsProfile: 'Profil',
    settingsSecurity: 'Sécurité',
    settingsNotifications: 'Notifications',
    settingsAccount: 'Compte',
    // Community Page
    communityTitle: 'Hub Communautaire',
    communitySubtitle: 'Connectez, partagez, apprenez et obtenez de l\'aide de l\'IA.',
    communityForum: 'Forum Communautaire',
    educationalHub: 'Hub Éducatif',
    agrobotAI: 'IA AgroBot',
    newPost: 'Nouveau Post',
    // Seasonal Calendar
    calendarTitle: 'Calendrier Agricole Saisonnier',
    calendarSubtitle: "Un guide professionnel des activités agricoles au Cameroun, adapté à vos besoins.",
    filterCrop: 'Culture',
    filterRegion: 'Région',
    downloadPrint: 'Télécharger/Imprimer',
  },
  pi: {
    home: 'Haus',
    marketplace: 'Maket',
    community: 'Community',
    seasonalCalendar: 'Calendar for Farm',
    about: 'About Wi',
    contactUs: 'Contact Wi',
    notifications: 'Notifications',
    markAllAsRead: 'Mark all as read',
    noNotifications: 'No notification yet.',
    viewAllNotifications: 'See all notification',
    dashboard: 'Dashboard',
    settings: 'Settings',
    adminPanel: 'Admin Panel',
    logout: 'Logot',
    login: 'Login',
    signUp: 'Sign Up',
    welcome: 'Welcome',
    dashboardGreeting: 'Na wetin di happen for your dashboard today be dis.',

    // Tabs
    tabOverview: 'Overview',
    tabListings: 'My Market',
    tabServices: 'My Service',
    tabOrders: 'Order wey di kam',
    tabBookings: 'Bookings',
    tabCommunity: 'Community',
    tabDisputes: 'My Palaver',
    tabAnalytics: 'Analytics',
    tabWallet: 'Wallet',
    tabVerification: 'Verification',
    tabMessages: 'Message',
    tabReviews: 'Reviews',
    tabMyOrders: 'My Order',
    tabMyBookings: 'My Booking',
    tabFavorites: 'Favorites',
    tabSavedArticles: 'Saved Books',
    tabCalendarAlerts: 'Calendar Alert',
    tabProfileAndVerification: 'Profile & Verification',
    tabFollowing: 'Following',
    tabRecipes: 'Recipe Helper',
    tabAdminAnalytics: 'Analytics',
    tabAdminFinances: 'Money Matter',
    tabAdminSecurity: 'Security Alert',
    tabAdminModeration: 'Moderation',
    tabAdminUsers: 'People',
    tabAdminListings: 'Market',
    tabAdminVerifications: 'Verification',
    tabAdminDisputes: 'Palaver',
    tabAdminContent: 'Content',
    tabAdminMap: 'Map View',
    tabAdminLogs: 'Activity Log',

    // Forms & Buttons
    addNewListing: 'Add New Market',
    addNewService: 'Add New Service',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm',
    submit: 'Submit',
    saveChanges: 'Save Change',
    search: 'Find',
    clearFilters: 'Clear All Filter',

    // Marketplace
    marketplaceTitle: 'Maket',
    marketplaceSubtitle: 'Discover fresh chop and service dem from local seller.',
    filtersTitle: 'Filters',
    gridView: 'Grid',
    mapView: 'Map',
    searchFilter: 'Find',
    regionFilter: 'Region',
    categoryFilter: 'Category',
    sortByFilter: 'Sort By',
    categoryAll: 'All',
    categoryVegetables: 'Vegetable',
    categoryFruits: 'Fruit',
    categoryGrains: 'Grains',
    categoryLivestock: 'Livestock',
    categoryPoultry: 'Poultry',
    categoryTools: 'Tool',
    categoryFertilizers: 'Fertilizer',
    categoryCrafts: 'Craft',
    categoryServices: 'Service',
    sortNewest: 'Newest One',
    sortPriceAsc: 'Price: Small to Big',
    sortPriceDesc: 'Price: Big to Small',

    // Footer
    footerTagline: 'Connect Cameroon farmer dem for world.',
    support: 'Support',
    faqLink: 'FAQ',
    termsLink: 'Terms of Service',
    privacyLink: 'Privacy Policy',
    feesPolicy: 'Fees & Commission Policy',
    newsletterTitle: 'Stay for Loop',
    newsletterDescription: 'Subscribe for the latest update for fresh chop, new service, and special offer.',
    subscribe: 'Subscribe',
    quickLinks: 'Quick Links',
    joinUs: 'Join Wi',
    joinAsFarmer: 'Join as Farmer',
    joinAsBuyer: 'Join as Buyer',
    joinAsServiceProvider: 'Join as Service Provider',
    // Login Page
    signInTitle: 'Sign in for your account',
    signInSubtitle: 'Or',
    startJourneyLink: 'start your journey with wi',
    rememberMe: 'Remember me',
    forgotPassword: 'Forget your password?',
    signInButton: 'Sign in',
    emailPlaceholder: 'Put ya email address',
    passwordPlaceholder: 'Put ya password',
    // Register Page
    createAccountTitle: 'Create your account',
    createAccountSubtitle: 'You get account already?',
    firstNameLabel: 'First Name',
    lastNameLabel: 'Last Name',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    roleLabel: 'I be...',
    buyerRole: 'Buyer',
    farmerRole: 'Farmer',
    serviceProviderRole: 'Service Provider',
    adminRole: 'Admin',
    supportAgentRole: 'Support Agent',
    createAccountButton: 'Create Account',
    restrictedRoleMessage: '🔒 Dis kain wok nid fo verify. Go login with ya correct details.',
    proceedToLoginButton: 'Go for Login',
    firstNamePlaceholder: 'e.g., John',
    lastNamePlaceholder: 'e.g., Doe',
    confirmPasswordPlaceholder: 'Confirm ya password',
    socialLoginSeparator: 'Or continue with',
    signUpWithGoogle: 'Sign up with Google',
    signUpWithFacebook: 'Sign up with Facebook',
    signUpWithApple: 'Sign up with Apple',
    iHaveReadAndAgree: 'I don read and gree for di',
    feesAndCommissionPolicyLink: 'Fees & Commission Policy',
    passwordWeak: 'Weak',
    passwordMedium: 'Medium',
    passwordStrong: 'Strong',
    passwordIsWeakError: 'Password e too weak.',
    // Cart Page
    cartTitle: 'Your Cart',
    removeItem: 'Remove',
    deliveryOptionsTitle: 'Delivery Options',
    orderSummaryTitle: 'Order Summary',
    walletBalance: 'Your balance',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery',
    orderTotal: 'Order total',
    estDelivery: 'Estimated Delivery',
    placeOrderButton: 'Place Order',
    continueShopping: 'Continue Shopping',
    // Settings Page
    settingsTitle: 'Account Settings',
    settingsProfile: 'Profile',
    settingsSecurity: 'Security',
    settingsNotifications: 'Notifications',
    settingsAccount: 'Account',
     // Community Page
    communityTitle: 'Community Hub',
    communitySubtitle: 'Connect, share, learn, and get AI-powered help.',
    communityForum: 'Community Forum',
    educationalHub: 'Educational Hub',
    agrobotAI: 'AgroBot AI',
    newPost: 'New Post',
    // Seasonal Calendar
    calendarTitle: 'Seasonal Task Calendar',
    calendarSubtitle: "A professional guide to agricultural activities in Cameroon, tailored to your needs.",
    filterCrop: 'Crop',
    filterRegion: 'Region',
    downloadPrint: 'Download/Print',
  },
};

type TranslationKey = keyof (typeof translations)['en'];

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
      const savedLang = localStorage.getItem('agroconnect_language');
      return (savedLang === 'en' || savedLang === 'fr' || savedLang === 'pi') ? savedLang : 'en';
  });

  const setLanguage = (lang: Language) => {
    localStorage.setItem('agroconnect_language', lang);
    setLanguageState(lang);
  };

  const t = useCallback((key: TranslationKey): string => {
    return translations[language][key] || translations['en'][key];
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
